### ISSUE TITLE
确认一个exec的问题

### ISSUE THREAD

**Issue by javyuan** [illuspas/nginx-rtmp-win32#13]
exec* not supported指的是exec_publish_done这种事件回调不支持？
有什么其它办法吗？

**Comment by illuspas** [comment]
阅读 ngx_rtmp_exec_module.c文件,最后面可以看到exec的所有Nginx函数链在WIN32下都是屏蔽了的.  
有能力可以实现这部分,主要是进程和信号

**Comment by javyuan** [comment]
谢谢你的回答，无奈自己水平不够对系统级别的代码接触为0。期待来位C大神完善吧。
