### ISSUE TITLE
NetConnection.Connect.Failed

### ISSUE THREAD

**Issue by wentaowanna** [illuspas/nginx-rtmp-win32#6]
你好，请问一下我在进那个直播测试工具的时候可以采集图像和音频信息，但是想推流的时候显示NetConnection event : NetConnection.Connect.Failed，请教一下这个是因为什么原因？另外，这个是封装好的，不知道有没有Demo的源码，望回答，谢谢！

**Comment by illuspas** [comment]
你检查下地址，直播测试工具现在有个问题是复制地址栏url，端口号会错误，8080删掉或者改成1935试试

**Comment by wentaowanna** [comment]
可以使用了，谢谢。不知道这个测试工具是放在哪一块呢？能够给一些思路或者代码？

**Comment by illuspas** [comment]
有源码呀，仔细看README

**Comment by wentaowanna** [comment]
抱歉，看是粗略看了一下以为那只有配置文件。小白还需多学习！谢谢分享！

**Comment by ayw8255** [comment]
确认了下端口号什么的，没有问题，仍然推不成功，提示：NetConnection event : NetConnection.Connect.Failed
